title: Alex Lee's Blog
description: "개인 블로그 & 프로젝트 문서 & 연구 노트"
baseurl: ""
url: "https://alexlee0213.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Site settings
lang: ko
author:
  name: Alex Lee

# Permalink
permalink: /:categories/:year/:month/:day/:title/

# Collections (나중에 프로젝트 문서, 연구과제용으로 확장 가능)
# collections:
#   projects:
#     output: true
#   research:
#     output: true
